version: '3'

services:
  # MinIO
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console UI
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  spark:
    image: bitnami/spark:latest
    container_name: spark
    environment:
      SPARK_MODE: master
    ports:
      - "7077:7077"  # Spark master port
      - "8081:8080"  # Spark UI
    volumes:
      - spark_data:/tmp/spark

volumes: 
  minio_data:
  postgres_data:
  spark_data:
